# Site settings
title: Quero Uma Loja
email: contato@queroumaloja.net
description: Quero Uma Loja é uma plataforma simples para sites que queiram vender online.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.queroumaloja.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
timezone: America/Sao_Paulo
permalink: pretty

# Pagination
paginate: 3
pagination_path: "/:num"

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed
